version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  print_var:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo $MyName
workflows:
  welcome:
    jobs:
      - print_hello
      - print_var
      - print_world:
          requires:
            - print_hello